name: mongo_dart_query
version: 0.4.2
description: Query builder for mongo_dart and objectory
homepage: https://github.com/mongo-dart/mongo_dart_query
environment:
  sdk: ">=2.5.2 <3.0.0"
dependencies:
  bson: "^0.3.2"
  meta: ^1.1.7
dev_dependencies:
  test: ^1.14.0
  pedantic: ^1.9.0
  #dart_coveralls: ">=0.4.0"
