name: mongo_dart_query
version: 0.3.1
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Joel Trottier-Hebert <iamquebecois@gmail.com>
description: Query builder for mongo_dart and objectory
homepage: https://github.com/mongo-dart/mongo_dart_query
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  bson: '^0.3.0'
  dart2_constant: '^1.0.0'
dev_dependencies:
  browser: '>=0.10.0'
  test: ">=0.12.10+2"
  dart_coveralls: ">=0.4.0"
